openfactory/datafabric/app/main/models/__init__.py
from openfactory.datafabric.app.main.models.tasks import RQTask
from openfactory.datafabric.app.main.models.notifications import Notification

openfactory/datafabric/app/main/models/notifications.py
from sqlalchemy import ForeignKey
from sqlalchemy import String
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship

from openfactory.datafabric.app import db
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from openfactory.datafabric.app.auth.models.users import User


class Notification(db.Model):
    """
    Notification model
    """

    __tablename__ = 'user_notifications'

    id: Mapped[int] = mapped_column(primary_key=True)
    message: Mapped[str] = mapped_column(String(80))
    type: Mapped[str] = mapped_column(String(80))
    user_id: Mapped[int] = mapped_column(ForeignKey('users.id'))
    user: Mapped['User'] = relationship(back_populates='notifications')

    def __repr__(self):
        return f"{self.user.username}: {self.message}"

openfactory/datafabric/app/main/models/tasks.py
import redis
import rq
from typing import Optional
from sqlalchemy import String
from sqlalchemy import ForeignKey
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship
from flask import current_app

from openfactory.datafabric.app import db
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from openfactory.datafabric.app.auth.models.users import User


class RQTask(db.Model):
    """
    RQ Task model
    """

    __tablename__ = 'rq_tasks'

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    name: Mapped[str] = mapped_column(String(128), index=True)
    description: Mapped[Optional[str]] = mapped_column(String(80))
    user_id: Mapped[int] = mapped_column(ForeignKey('users.id'))
    user: Mapped['User'] = relationship(back_populates='tasks')
    complete: Mapped[bool] = mapped_column(default=False)

    def get_rq_job(self):
        """ Return RQ job or None if job does not exist """
        try:
            rq_job = rq.job.Job.fetch(self.id, connection=current_app.redis)
        except (redis.exceptions.RedisError, rq.exceptions.NoSuchJobError):
            return None
        return rq_job

openfactory/datafabric/app/main/__init__.py
"""
DataFabric Main blueprint
"""
from flask import Blueprint
from openfactory.datafabric.app import admin_app, db
from openfactory.datafabric.app.main.models.notifications import Notification
from openfactory.datafabric.app.main.models.tasks import RQTask
from openfactory.datafabric.app.main.views.notificationview import NotificationView
from openfactory.datafabric.app.main.views.taskview import RQTaskView

main_blueprint = Blueprint('main', __name__,
                           template_folder='templates',
                           static_folder='static',
                           static_url_path='/static/main')

def create_bp(app):
    """ Blueprint factory """
    # register models to admin app
    admin_app.add_view(RQTaskView(RQTask, db.session, name='RQ-Task'))
    admin_app.add_view(NotificationView(Notification, db.session, name='User Notifications'))

    # register blueprint
    app.register_blueprint(main_blueprint)

from openfactory.datafabric.app.main import routes

openfactory/datafabric/app/main/routes.py
"""
Routes for DataFabric Main Blueprint
"""
from flask_login import login_required, current_user
from flask import render_template
from openfactory.datafabric.app import db
from openfactory.datafabric.app.main import main_blueprint
from openfactory.datafabric.app.main.models.notifications import Notification


@main_blueprint.route('/')
@main_blueprint.route('/index')
@login_required
def index():
    """ Home page of DataFabric """
    return render_template('index.html',
                           title='Home')


@main_blueprint.route('/rq_tasks')
@login_required
def rq_tasks():
    """ Returns all rq-tasks in progress of current user """
    tasks = current_user.get_RQ_tasks_in_progress()
    return [{'name': t.name,
             'id': t.id,
             'description': t.description} for t in tasks]


@main_blueprint.route('/new_user_notifications')
@login_required
def new_user_notifications():
    """ Returns 1 if new notifications 0 if none """
    notifications = current_user.count_notifications()
    print(notifications)
    if notifications > 0:
        return '1'
    else:
        return '0'


@main_blueprint.route('/user_notifications')
@login_required
def user_notifications():
    """ Returns all user notifications """
    notifications = current_user.get_notifications()
    return [{'id': n.id,
             'message': n.message,
             'type': n.type} for n in notifications]


@main_blueprint.route('/user_notification/<notification_id>/remove')
@login_required
def user_notification_remove(notification_id):
    """ Remove user notifications and returns updated ones """
    notification = db.get_or_404(Notification, notification_id, description="This notification doesn't exist")
    db.session.delete(notification)
    db.session.commit()
    notifications = current_user.get_notifications()
    return [{'id': n.id,
             'message': n.message,
             'type': n.type} for n in notifications]

openfactory/datafabric/app/main/rq_tasks/__init__.py
from openfactory.datafabric.app import create_app

app = create_app()
app.app_context().push()

from openfactory.datafabric.app.main.rq_tasks.node_up import node_up
from openfactory.datafabric.app.main.rq_tasks.node_down import node_down
from openfactory.datafabric.app.main.rq_tasks.compose_up import compose_up
from openfactory.datafabric.app.main.rq_tasks.compose_down import compose_down
from openfactory.datafabric.app.main.rq_tasks.add_stack import add_stack
from openfactory.datafabric.app.main.rq_tasks.agent_up import agent_up
from openfactory.datafabric.app.main.rq_tasks.agent_down import agent_down
from openfactory.datafabric.app.main.rq_tasks.load_agent_stack import load_agent_stack

openfactory/datafabric/app/main/views/notificationview.py
from flask_admin.contrib.sqla import ModelView


class NotificationView(ModelView):
    """
    Admin View for User Notification Model
    """
    can_create = False
    can_edit = False

    form_columns = ['user', 'message', 'type']
    column_list = ['id', 'user', 'message', 'type']

openfactory/datafabric/app/main/views/taskview.py
from flask_admin.contrib.sqla import ModelView


class RQTaskView(ModelView):
    """
    Admin View for RQ Task Model
    """
    can_create = False
    can_edit = False

    form_columns = ['id', 'name', 'description', 'user', 'complete']
    column_list = ['id', 'name', 'description', 'user', 'complete']
    column_labels = {'id': 'RQ ID',
                     'user': 'Task Owner'}

openfactory/datafabric/app/main/templates/base.html
<!DOCTYPE html>
<html style="height:100%;">
    <head>
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% if title %}
           <title>{{ title }} - DataFabric</title>
        {% else %}
           <title>DataFabric</title>
        {% endif %}

        <!-- Font Awesome 4 CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <!-- Bootstrap CSS -->
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
            integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
            crossorigin="anonymous">

        <!-- Base CSS -->
        <link rel="stylesheet" href="{{ url_for('main.static', filename='css/base.css') }}">

        <!-- Sidebar CSS -->
        <link rel="stylesheet" href="{{ url_for('main.static', filename='css/sidebar.css') }}">
        
    </head>



    <body class="d-flex flex-column h-100">

        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script
            src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous">
        </script>
        <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous">
        </script>
        <script 
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous">
        </script>
        
        <!-- Navbar -->
        <header>
            {% include 'navbar.html' %}
        </header>

        <!-- Flash messages -->
        {% include 'flash.html' %}
        
        <!-- Space for App -->
        <main class="flex-grow-1 d-flex" style="overflow: hidden;">
            {% block app_content %}
            {% endblock app_content %}
        </main>
        
        <!-- Footer -->
        {% include 'footer.html' %}

        <!-- Scripts -->
        <script>
            {% include 'scripts.html' %}
        </script>
      
  </body>
    
</html>

openfactory/datafabric/app/main/templates/bootstrap_wtf.html
{% macro form_field(field, autofocus) %}
  {%- if field.type == 'BooleanField' %}
      <div class="form-check mb-3">
        {{ field(class='form-check-input') }}:
        {{ field.label(class='form-check-label') }}
      </div>

  {%- elif field.type == 'RadioField' %}
      {{ field.label(class='form-label') }}
      {%- for item in field %}
      <div class="form-check{% if loop.last %} mb-3{% endif %}">
        {{ item(class='form-check-input') }}:
        {{ item.label(class='form-check-label') }}
      </div>
      {%- endfor %}
  
  {%- elif field.type == 'SelectField' %}
      {{ field.label(class='form-label') }}:
      {{ field(class='form-select mb-3') }}
  
  {%- elif field.type == 'TextAreaField' %}
      <div class="mb-3">
        {{ field.label(class='form-label') }}:
        {% if autofocus %}
          {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
        {% else %}
          {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
        {% endif %}
        {%- for error in field.errors %}
          <div class="invalid-feedback">{{ error }}</div>
        {%- endfor %}
      </div>

  {%- elif field.type == 'SubmitField' %}
      {{ field(class='btn btn-success mb-3') }}

  {%- else %}
      <div class="mb-3">
        <span data-toggle="tooltip" data-placement="right" title="{{ field.description }}">
          {{ field.label(class='form-label') }}:
        </span>
        {% if autofocus %}
          {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
        {% else %}
          {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
        {% endif %}
        {%- for error in field.errors %}
          <div class="invalid-feedback">{{ error }}</div>
        {%- endfor %}
      </div>
  {%- endif %}
{% endmacro %}

<!-- quick_form macro 
  Usage: quick_form(form, action="", method="post", id="", novalidate=False, enctype="")
        form: WTFform
        action, method, id, novalidate, encotype: options passed to HTML -->
{% macro quick_form(form, action="", method="post", id="", novalidate=False, enctype="") %}
<form novalidate
  {%- if action != None %} action="{{ action }}"{% endif -%}
  {%- if method %} method="{{ method }}"{% endif %}
  {%- if id %} id="{{ id }}"{% endif -%}
  {%- if novalidate %} novalidate{% endif -%}
  {%- if enctype %} enctype="{{ enctype }}" {% endif -%}>
  {{ form.hidden_tag() }}
  {%- for field, errors in form.errors.items() %}
    {%- if form[field].widget.input_type == 'hidden' %}
      {%- for error in errors %}
        <div class="invalid-feedback">{{ error }}</div>
      {%- endfor %}
    {%- endif %}
  {%- endfor %}

  {% set ns = namespace(first_field=true) %}
  {%- for field in form %}
    {% if field.widget.input_type != 'hidden' -%}
      {{ form_field(field, ns.first_field) }}
      {% set ns.first_field = false %}
    {%- endif %}
  {%- endfor %}  
</form>
{% endmacro %}

openfactory/datafabric/app/main/templates/flash.html
<!-- RQ Tasks in progress -->
{% if current_user.is_authenticated %}
  {% with tasks = current_user.get_RQ_tasks_in_progress() %}
    {% if tasks %}
      <span id="user_rq_tasks">
      {% for task in tasks %}
        <div class="alert alert-info">
           <img src="{{ url_for('main.static', filename='figures/loading.gif') }}">  {{ task.description }}
        </div>
      {% endfor %}
      </span>
    {% endif %}
  {% endwith %}
{% endif %}

<!-- User notifications -->
{% if current_user.is_authenticated %}
   <span id="user_notifications"></span>
{% endif %}

<!-- Flash messages -->
{% with msg = get_flashed_messages(with_categories=True) %}
    {% if msg %}
        {% for category, message in msg %}
            <div class="alert alert-{{ category }} alert-dismissible">
              <strong>{{ message }}</strong>
              <button type="button" class="close" data-dismiss="alert">&times;</button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

openfactory/datafabric/app/main/templates/footer.html
<!-- templates/footer.html -->

<footer class="footer sticky-bottom bg-light" style="padding: 15px;">
    <span class="text-muted">(c) 2024 Rolf Wuthrich - Concordia University</span>
</footer>

openfactory/datafabric/app/main/templates/index.html
{% extends "base.html" %}

{% block app_content %}
<div>
    <h1>Welcome to OpenFactory</h1>
    <br>
    <img src="{{ url_for('main.static', filename='figures/DataFlow.png') }}" 
         alt="OpenFactory" 
         style="width: 90%; margin: 0 auto; display: block;" />
</div>
{% endblock app_content %}

openfactory/datafabric/app/main/templates/navbar.html
<!-- templates/navbar.html -->

<!-- Navigation bar on top -->
<nav class="navbar navbar-expand-md sticky-top navbar-dark" style="background-color: #962B09;">
  <a class="navbar-brand" href="{{ url_for('main.index') }}">DataFabric</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarMenus" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarMenus">
    <ul class="navbar-nav active">
      <li class="nav-item">
          <a class="nav-link" style="color: #FFFFFF" href="{{ url_for('main.index') }}">Home</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" style="color: #FFFFFF" href="{{ url_for('infra.home') }}">Infrastructure</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" style="color: #FFFFFF" href="{{ url_for('services.home') }}">Services</a>
      </li>
    </ul>

    <ul class="navbar-nav active ml-auto">
      <li class="nav-item">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ current_user.fullname }}
          </a>
          <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('main.index') }}">Settings</a>
              <a class="dropdown-item" href="{{ url_for('admin.index') }}">Admin</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Log Out</a>
          </div>
      </li>
    </ul>
  </div>

</nav>

openfactory/datafabric/app/main/templates/scripts.html
<!-- General scripts -->

<!-- Tooltips (Bootstrap 4) initialization with jQuery -->
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
});

<!-- Remove a user notifications -->
async function rm_user_notification(notification_id) {
  const url = "{{ url_for('main.user_notification_remove', notification_id='NOTE_ID') }}".replace("NOTE_ID", notification_id)
  const response = await fetch(url);
  display_user_notifications(await response.json());
}

<!-- Display user notifications -->
function display_user_notifications(notifications) {
  var html = "";
  notifications.forEach(n => html += 
     '<div class="alert alert-' + n.type + ' alert-dismissible">' +
      n.message + '<button type="button" class="close" onclick="rm_user_notification(' + n.id + ')" data-dismiss="alert">&times;</button></div>');
  const notifications_Element = document.getElementById("user_notifications");
  notifications_Element.innerHTML = html;
}


<!-- Load and display user notifications -->
async function load_user_notifications() {
  const response = await fetch("{{ url_for('main.user_notifications') }}");
  display_user_notifications(await response.json())
}
document.addEventListener('DOMContentLoaded', load_user_notifications);


<!-- Pools perdiodically user notifications and rq-tasks and updates them as required -->
{% if current_user.is_authenticated %}
function update_rq_tasks() {
   setInterval(async function() {
      const r = await fetch("{{ url_for('main.new_user_notifications') }}");
      const n = await r.json();
      if (n == '1') {load_user_notifications()};
      const response = await fetch("{{ url_for('main.rq_tasks') }}");
      const tasks = await response.json();
      const rq_tasks_Element = document.getElementById("user_rq_tasks");
      var tasks_text = "";
      tasks.forEach(t => tasks_text += '<div class="alert alert-info"><img src="{{ url_for('main.static', filename='figures/loading.gif') }}"> ' + t.description + '</div>');
      rq_tasks_Element.innerHTML = tasks_text;
    }, 3000);
}
document.addEventListener('DOMContentLoaded', update_rq_tasks);
{% endif %}